<?php
include_once("Object.php");
include_once("WHException.php");
include_once("WHMultipleInheritance.php");
include_once("WHAssociation.php");
include_once("WHError.php");
include_once("WHDate.php");
include_once("WHTime.php");
include_once("WHDateAndTime.php");
